require_relative '../key_for_min'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # config here
end

def key_for_min_value(name_hash)
lowest_key = nil 
  lowest_value = nil 
  name_hash.each do |key, value|
    if lowest_value == nil || value < lowest_value
      lowest_value = value 
      lowest_key = key 
    end
  end
  lowest_key
end